# Generated by Django 2.0 on 2017-12-07 04:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='term',
            name='k',
        ),
        migrations.AddField(
            model_name='document',
            name='path',
            field=models.FilePathField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=140, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='occurrence',
            unique_together={('term', 'document')},
        ),
        migrations.AddField(
            model_name='correlation',
            name='term1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_set_term1',
                                    to='engine.Term'),
        ),
        migrations.AddField(
            model_name='correlation',
            name='term2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_set_term2',
                                    to='engine.Term'),
        ),
        migrations.AlterUniqueTogether(
            name='correlation',
            unique_together={('term1', 'term2')},
        ),
    ]
