# Generated by Django 2.0 on 2017-12-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
